import { chromium } from 'playwright-core';
import { mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer } from '../server.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'mockups');
await mkdir(out, { recursive: true });
const server = createServer();
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
let browser;
try {
  browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true, args: ['--no-sandbox', '--enable-webgl', '--use-gl=angle', '--use-angle=swiftshader'] });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
  const browserErrors = [];
  page.on('pageerror', err => browserErrors.push(err.message));
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  await page.waitForTimeout(900);
  await page.getByRole('heading', { name: /YOUR UNIVERSE/ }).waitFor();
  await page.screenshot({ path: path.join(out, 'landing.png') });
  await page.locator('#guest-start').click();
  await page.locator('#daily.active').waitFor();
  await page.screenshot({ path: path.join(out, 'daily_compass.png'), fullPage: true });
  await page.locator('#period-horizon').selectOption('month');
  await page.locator('#period-topic').selectOption('career');
  await page.locator('#period-load').click();
  await page.locator('#period-result:not(.hidden)').waitFor();
  await page.waitForFunction(() => document.querySelector('#period-signal')?.textContent.trim());
  if (!(await page.locator('#period-signal').textContent()).trim()) throw new Error(`Period reading was empty: ${await page.locator('#period-result').innerText()}`);
  await page.screenshot({ path: path.join(out, 'period_career.png'), fullPage: true });
  await page.getByRole('button', { name: /Why this reading/ }).click();
  await page.screenshot({ path: path.join(out, 'why_this_reading.png'), fullPage: true });
  await page.getByRole('button', { name: /Back to reading/ }).click();
  await page.getByRole('button', { name: /Reflect on today/ }).click();
  await page.screenshot({ path: path.join(out, 'reflection.png'), fullPage: true });
  await page.getByRole('radio', { name: 'Relevant' }).check();
  await page.getByRole('radio', { name: 'Yes' }).check();
  await page.locator('#reflection-note').fill('A short private test note.');
  await page.getByRole('button', { name: /Save reflection/ }).click();
  await page.getByText('Your reflection is saved on this device.').waitFor();
  await page.reload();
  if (await page.locator('#reflection-note').inputValue() !== 'A short private test note.') throw new Error('Reflection did not persist');
  await page.getByRole('button', { name: 'Clear my local data' }).click();
  if (await page.evaluate(() => localStorage.length) !== 0) throw new Error('Local data was not cleared');
  await page.getByRole('button', { name: /Start again/ }).click();
  await page.locator('#profile-toggle').click();
  await page.screenshot({ path: path.join(out, 'onboarding.png'), fullPage: true });
  await page.locator('#birth-date').fill('1998-04-10');
  await page.locator('#birth-time').fill('12:00');
  await page.locator('#birth-lat').fill('13.7563');
  await page.locator('#birth-lon').fill('100.5018');
  await page.locator('#birth-consent').check();
  await page.locator('#western-chart').click();
  await page.locator('.profile-result:not(.hidden) .placement').nth(0).waitFor();
  if (await page.locator('.profile-result .placement').count() < 12) throw new Error('Western placements were not rendered');
  await page.screenshot({ path: path.join(out, 'western_chart.png'), fullPage: true });
  await page.locator('#vedic-chart').click();
  await page.getByText(/Current major period:/).waitFor();
  await page.screenshot({ path: path.join(out, 'vedic_timing.png'), fullPage: true });
  const sensitive = await page.evaluate(() => JSON.stringify(localStorage));
  if (sensitive.includes('1998-04-10') || sensitive.includes('13.7563')) throw new Error('Birth data was persisted');
  await page.getByRole('button', { name: 'Start again' }).click();
  await page.getByRole('button', { name: /Ask the Oracle/ }).click();
  await page.screenshot({ path: path.join(out, 'ask_oracle.png'), fullPage: true });
  await page.locator('#oracle-question').fill('Will I get the job I interviewed for?');
  await page.locator('#oracle-submit').click();
  await page.locator('.oracle-answer .oracle-cards').waitFor();
  if (await page.locator('.oracle-answer .mini-card').count() !== 3) throw new Error('Ask Oracle did not return the career Tarot spread');
  await page.screenshot({ path: path.join(out, 'oracle_answer.png'), fullPage: true });
  const afterTarot = await page.evaluate(() => JSON.stringify(localStorage));
  if (afterTarot.includes('Will I get the job')) throw new Error('Question was persisted');
  await page.locator('#nav-iching').click();
  await page.locator('#iching-question').fill('A or B: should I accept this role?');
  await page.locator('#iching-cast').click();
  await page.locator('#iching-result .hexagram-output').waitFor();
  await page.screenshot({ path: path.join(out, 'iching_cast.png'), fullPage: true });
  await page.locator('#nav-tarot').click();
  await page.locator('#tarot-question').fill('How should I approach my budget this month?');
  await page.locator('input[name="spread"][value="money"]').check();
  await page.locator('#draw-tarot').click();
  await page.locator('.tarot-card').nth(0).waitFor();
  if (await page.locator('.tarot-card').count() !== 3) throw new Error('Tarot did not draw the requested three-card spread');
  await page.locator('.tarot-card').nth(0).click();
  if (!(await page.locator('.tarot-card').nth(0).getAttribute('class')).includes('revealed')) throw new Error('Tarot reveal interaction failed');
  await page.screenshot({ path: path.join(out, 'tarot_question.png'), fullPage: true });
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, reducedMotion: 'reduce' });
  mobile.on('pageerror', err => browserErrors.push(err.message));
  await mobile.goto(`http://127.0.0.1:${server.address().port}`);
  await mobile.screenshot({ path: path.join(out, 'landing_mobile.png') });
  const overflow = await mobile.evaluate(() => document.documentElement.scrollWidth - innerWidth);
  if (overflow > 2) throw new Error(`Mobile layout overflows by ${overflow}px`);
  await mobile.locator('#guest-start').click();
  await mobile.locator('#daily.active').waitFor();
  await mobile.locator('[data-go="ask"]').click();
  await mobile.locator('#oracle-question').fill('คนเก่าจะกลับมาไหม');
  await mobile.locator('#oracle-submit').click();
  await mobile.locator('.oracle-answer .oracle-cards').waitFor();
  const mobileAskOverflow = await mobile.evaluate(() => document.documentElement.scrollWidth - innerWidth);
  if (mobileAskOverflow > 2) throw new Error(`Mobile Ask view overflows by ${mobileAskOverflow}px`);
  await mobile.locator('[data-go="tarot"]').click();
  await mobile.locator('#tarot-question').fill('ความสัมพันธ์นี้ควรทบทวนอะไร');
  await mobile.locator('input[name="spread"][value="relationship"]').check();
  await mobile.locator('#draw-tarot').click();
  await mobile.locator('.tarot-card').nth(0).waitFor();
  const mobileTarotOverflow = await mobile.evaluate(() => document.documentElement.scrollWidth - innerWidth);
  if (mobileTarotOverflow > 2) throw new Error(`Mobile Tarot view overflows by ${mobileTarotOverflow}px`);
  await mobile.locator('[data-go="iching"]').click();
  await mobile.locator('#iching-question').fill('ฉันควรให้ความสำคัญกับอะไร');
  await mobile.locator('#iching-cast').click();
  await mobile.locator('#iching-result .hexagram-output').waitFor();
  const mobileIChingOverflow = await mobile.evaluate(() => document.documentElement.scrollWidth - innerWidth);
  if (mobileIChingOverflow > 2) throw new Error(`Mobile I Ching view overflows by ${mobileIChingOverflow}px`);
  await mobile.locator('[data-go="onboard"]').click();
  await mobile.locator('#birth-date').fill('1990-06-15');
  await mobile.locator('#birth-time').fill('12:00');
  await mobile.locator('#birth-lat').fill('13.7563');
  await mobile.locator('#birth-lon').fill('100.5018');
  await mobile.locator('#birth-consent').check();
  await mobile.locator('#vedic-chart').click();
  await mobile.locator('.profile-result .placement').nth(0).waitFor();
  const mobileChartOverflow = await mobile.evaluate(() => document.documentElement.scrollWidth - innerWidth);
  if (mobileChartOverflow > 2) throw new Error(`Mobile chart view overflows by ${mobileChartOverflow}px`);
  if (browserErrors.length) throw new Error(`Browser errors: ${browserErrors.join(' | ')}`);
  console.log(`Saved browser screenshots to ${out}`);
} finally {
  await browser?.close();
  await new Promise(resolve => server.close(resolve));
}
